version: '3'
services:
  testsuite:
    image: "denvazh/gatling:3.2.1"
    command: -m
    #stdin_open: true
    #tty: true
    environment:
      # Variabler som skickas vidare till containern
      - TARGETHOST
      - RPS
      - DIRECT_RPS
      - UPDATE20_USERS
      - UPDATE1000_PAUSE
      - DURATION_MINUTES
      - AGG10_RPS_MIN
      - AGG10_RPS_MAX
      - UPDATE_RPS_MIN
      - UPDATE_RPS_MAX
      - ERR3_REQ

    volumes:
      - ./conf:/opt/gatling/conf
      - ./user-files:/opt/gatling/user-files
      - ./results:/opt/gatling/results
    entrypoint: ["sh", "/opt/gatling/user-files/chown-files.sh"]
  recorder:
    image: "denvazh/gatling"
    # bash är inte istallerat i containern, så måste explict köra sh
    entrypoint: ["sh", "/opt/gatling/bin/recorder.sh"]
    # För exempelkommandon:
    # docker compose run --rm recorder --help
    command: -cli true -lp 8000
    ports:
      - "8000:8000"
    volumes:
      - ./user-files:/opt/gatling/user-files
